Repository urLink-DEV/urLink-frontend, pull requests merged in 2020-07, with the labels that each got.

#94 Feature/category tab
  src/components/category.js
  src/components/category/CategoryDrawer.js
  src/components/category/CategoryHistory.js
  src/components/category/CategoryHistoryDrawer.js
  src/components/category/CategoryTab.js
  src/components/category/styles/CategoryDrawer.js
  src/components/category/styles/CategoryTab.js
  src/containers/LoginContainer.js
  src/containers/SignupContainer.js
  src/containers/category/CategoryContainer.js
  src/pages/SignupPage.js
  src/pages/_CategoryPage.js
  src/pages/category/Category.scss
Labels: Front-Component, bug, bug-fix, help wanted

#95 Hotfix/page& component
  src/App.js
  src/commons/validation/register.js
  src/components/MsgAlert.js
  src/components/alert.js
  src/components/button.js
  src/components/category/CategoryAppBar.js
  src/components/category/CategoryCard.js
  src/components/category/CategoryDrawer.js
  src/components/category/CategoryHistory.js
  src/components/category/CategoryHistoryDrawer.js
  src/components/category/CategoryTab.js
  src/components/category/styles/CategoryHistory.js
  src/components/input.js
  src/components/modal.js
  src/components/popover/AlarmPopover.js
  src/components/popover/ProfilePopOver.js
  src/components/popover/styles/ProfilePopOver.js
  src/containers/category/CategoryContainer.js
  src/contexts/ProfileContext.js
  src/pages/GetStartPage.js
  src/pages/LoginPage.js
  src/pages/MainPage.js
  src/pages/SignupPage.js
  src/pages/styles/GetstartPage.js
  src/pages/styles/LoginSignup.scss
  src/pages/styles/swiper.scss
  src/test/SingupTest.js
Labels: Front-Component, bug-fix, enhancement, 디자이너

#96 Feature/category tab
  src/components/category/CategoryDrawer.js
  src/components/category/CategoryTab.js
Labels: Front-Component, enhancement

#98 Hotfix/api
  src/commons/apis/alarm.js
  src/commons/apis/alarmSocket.js
  src/commons/apis/category.js
  src/commons/apis/link.js
  src/commons/apis/user.js
  src/commons/queryData.js
  src/components/Snackbar.js
  src/components/category/CategoryCard.js
  src/components/category/CategoryDrawer.js
  src/components/category/CategoryTab.js
  src/components/popover/AlarmPopover.js
  src/containers/category/CategoryContainer.js
  src/contexts/ProfileContext.js
Labels: Front-Common, bug-fix, enhancement, help wanted

#100 API CAll reduce & Bug-fix
  public/manifest.json
  src/commons/apis/alarmSocket.js
  src/commons/chromeApis/history.js
  src/commons/queryData.js
  src/components/category/CategoryDrawer.js
  src/containers/LoginContainer.js
  src/containers/category/CategoryContainer.js
Labels: bug-fix

#102 Feature/user & image update
  src/components/category/CategoryAppBar.js
  src/components/category/CategoryTabDrawer.js
  src/components/modal.js
  src/components/popover/AlarmPopover.js
  src/components/popover/ProfilePopOver.js
  src/components/popover/styles/AlarmPopover.js
  src/containers/category/CategoryContainer.js
  src/contexts/ProfileContext.js
  src/images/linkListEmptyIcon.png
  src/images/main1.png
  src/images/main1_back.png
  src/images/main2.png
  src/images/main2_back.png
  src/images/main3.png
  src/images/main3_back.png
Labels: Front-Component, bug-fix

#109 drag block ,none [D] &dragStart no target return
  src/components/category/CategoryTabDrawer.js
Labels: bug-fix

#110 card delete -> getLink, getCategory Call
  src/components/category/CategoryDrawer.js
Labels: bug-fix
